### ISSUE TITLE
TabbedPage example crashes

### ISSUE THREAD

**Issue by eylvisaker** [dotnet/maui-samples#300] opened 2022-11-28 05:12 UTC
I'm playing with the Controls Gallery (maui-samples\6.0\UserInterface\ControlGallery) and I noticed this issue. When running on Windows, the TabbedPage example crashes with an unhandled exception when I click the Green tab at the top. The exception has message "Value does not fall within the expected range." and a null StackTrace.

**Comment by jfversluis** [comment] 2023-11-07 14:28
Can't reproduce anymore, I think this is fixed on the .NET MAUI side, thanks!

**Closed by jfversluis** 2023-11-07 14:28 UTC
